# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array1 = np.zeros((10, ))
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(array1.dtype)

float64


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array2 = np.zeros((10, ))
array2[4]=1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array3 = np.arange(start=10, stop=50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
sort_array3_desc = np.sort(array3)[::-1]
print(sort_array3_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
array4 = np.arange(9)
array5 = array4.reshape(3, 3)
print(array5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array6 = np.array([1,2,0,0,4,0])
array6 != 0
boolean_indexes = np.array([ True,  True, False, False,  True, False])
array61 = array6[boolean_indexes]
print(array61)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
array7 = np.eye(3)
print(array7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
import numpy as np
print(np.random.rand(3,3))

[[0.41221806 0.00514627 0.93192325]
 [0.7675969  0.24609541 0.58516908]
 [0.35458068 0.08003718 0.03039495]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array8 = np.random.rand(10, 10)
print(array8)
print(np.amin(array8), np.amax(array8))

[[0.73714893 0.56436958 0.66102687 0.65767879 0.87590243 0.21323293
  0.62224888 0.47053863 0.8354206  0.47138027]
 [0.91489546 0.24920869 0.8833384  0.55276723 0.28014629 0.81110666
  0.15314255 0.54054847 0.23510594 0.53195555]
 [0.09020908 0.45547463 0.61012729 0.65348374 0.51247024 0.60158102
  0.92698897 0.35759757 0.41409783 0.26692932]
 [0.5002903  0.40814612 0.21060474 0.40449791 0.53465048 0.07713303
  0.55847919 0.79233162 0.41185497 0.12149253]
 [0.43892264 0.93294144 0.87082753 0.15724729 0.86818361 0.55326851
  0.4829366  0.67238301 0.5739875  0.82728322]
 [0.01311203 0.80332012 0.37170467 0.61547517 0.38219787 0.50170554
  0.59814314 0.68892894 0.87291494 0.96596961]
 [0.80640007 0.11255991 0.82400164 0.90523    0.31561947 0.60596597
  0.94239779 0.72480718 0.19270305 0.70776788]
 [0.28879917 0.79931619 0.73807767 0.87263599 0.06709358 0.55906505
  0.70056971 0.88686965 0.68247964 0.1054671 ]
 [0.12526066 0.81749499 0.08005181 0.52683103 0.92745144 0.40694166
  0.69906537

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array9 = np.random.rand(30)
print(array9)
print("mean value:", np.mean(array9))

[0.56293763 0.4259104  0.14957652 0.96874604 0.18664432 0.64064113
 0.15522946 0.0704525  0.94425045 0.94876175 0.77242562 0.57031074
 0.91782795 0.86643337 0.9883657  0.13263305 0.18432535 0.27997151
 0.74255594 0.18106227 0.1674436  0.02274291 0.81600837 0.50445235
 0.57775346 0.02340291 0.38545858 0.99593207 0.65223962 0.24456608]
mean value: 0.5026353889211429


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array10 = np.array([[1,1,1],
    [1,0,1],
                   [1,1,1]])
print(array10)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False



In [ ]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array11 = np.diag([1,2,3,4], -1)
print(array11)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array12 = np.zeros((8, 8))
array12[::2, 1::2]=1
array12[1::2,::2]=1
print(array12)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
array13 = np.unravel_index([100], (6,7,8))
print(array13)

(array([1]), array([5]), array([4]))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array14 = np.arange(25).reshape(5,5)
array15 = (array14-np.mean(array14)/np.var(array14))
print(array15)

[[-0.23076923  0.76923077  1.76923077  2.76923077  3.76923077]
 [ 4.76923077  5.76923077  6.76923077  7.76923077  8.76923077]
 [ 9.76923077 10.76923077 11.76923077 12.76923077 13.76923077]
 [14.76923077 15.76923077 16.76923077 17.76923077 18.76923077]
 [19.76923077 20.76923077 21.76923077 22.76923077 23.76923077]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
import numpy as np
array151 = np.dtype([("r", np.uint8), ("g", np.uint8),  ("b", np.uint8),  ("a", np.uint8)])
print(array151)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
array14 = np.random.rand(5,3)
array15 = np.random.rand(3,2)
print(np.dot(array14, array15))

[[1.04336753 1.30144135]
 [1.27898563 1.3207435 ]
 [0.69612626 0.84385375]
 [0.85359608 0.88596127]
 [0.48643429 0.67825268]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array16 = np.random.randint(0, 10, 6)
array16[(array16<8) & (array16>3)]*=-1
print(array16)

[ 2  1  3  2 -6 -5]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


9,
10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z              <-legal
2 << Z >> 2       <-legal
Z <- Z            <-illegal
1j*Z              <-legal
Z/1/1             <-legal
Z<Z>Z             <-illegal

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
array(nan)
array(0)
array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 3 5 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.random.randint(0, 10, 5).astype(float)
B = np.random.randint(0, 10, 5).astype(float)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=A)

array([-67.5, -40. , -45.5,  -7. , -48. ])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
array17 = np.random.uniform(0,10,5)
print(array17//1)

[8. 8. 0. 4. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
array18 = np.tile(np.arange(5), (5,1))
print(array18)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array19 = np.random.rand(10)
array19.sort()
print(array19)

[0.46119749 0.4769957  0.55570518 0.62773198 0.64656299 0.69655652
 0.70258896 0.74880502 0.80838537 0.94465264]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
array20 = np.random.rand(10, 2)
a = np.sqrt(array20[:,0]**2+ array20[:,1]**2)
b = np.arctan2(array20[:,1],array20[:,0])
print(array20)
print(a)
print(b)


[[0.13861681 0.60603899]
 [0.50526812 0.3472515 ]
 [0.63230878 0.28624346]
 [0.45581347 0.5465337 ]
 [0.79030948 0.10277926]
 [0.37724736 0.03477717]
 [0.02201252 0.86173913]
 [0.6016663  0.99679845]
 [0.29046541 0.72766498]
 [0.81889489 0.44210042]]
[0.62168953 0.6130901  0.69408192 0.71166355 0.79696465 0.37884696
 0.86202023 1.16430644 0.78349631 0.93061357]
[1.34593837 0.60212561 0.42509341 0.87566003 0.12932357 0.09192684
 1.54525758 1.02773489 1.19100166 0.49503604]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
array21 = np.random.rand(10)
array21[array21.argmax()]=0
print(array21)

[1.66085357e-01 3.23610268e-01 6.85286445e-02 2.22980317e-01
 9.28042356e-01 0.00000000e+00 6.95880252e-01 2.32034111e-02
 8.54938199e-01 1.95102219e-04]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
array22 = np.arange(100)
array23 = np.random.uniform(0,100)
closest = array22[(np.abs(array22-array23)).argmin()]
print(array23)
print(closest)


65.6313618197297
66


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z[Z[:,0].argsort()])

[[1 1 7]
 [3 5 4]
 [6 5 1]]


In [ ]:
# column 2


In [ ]:
print(Z[Z[:,1].argsort()])

[[1 1 7]
 [6 5 1]
 [3 5 4]]


In [ ]:
# column 3


In [ ]:
print(Z[Z[:,2].argsort()])

[[6 5 1]
 [3 5 4]
 [1 1 7]]
