#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
array14 = np.random.rand(5,3)
array15 = np.random.rand(3,2)
print(np.dot(array14, array15))

[[1.84239032 1.25136845]
 [1.20408689 1.1049693 ]
 [0.86776473 0.70420726]
 [0.6946598  0.50769307]
 [0.8988537  1.09453834]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array16 = np.random.randint(0, 10, 6)
array16[(array16<8) & (array16>3)]*=-1
print(array16)

[ 2 -7  1  0  9 -5]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9,10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

```
Z**Z              <-legal
2 << Z >> 2       <-legal
Z <- Z            <-illegal
1j*Z              <-legal
Z/1/1             <-legal
Z<Z>Z             <-illegal
```

In [ ]:
Z**Z              <-legal
2 << Z >> 2       <-legal
<<: 2의 거듭제곱 곱하기   x << n  =  x * 2^n
>>: 2의 거듭제곱 나누기   x >> n = x / 2^n
Z <- Z            <-illegal    (<-는 존재 안함)
1j*Z              <-legal      [1j, 2j, 3j]
Z/1/1             <-legal
Z<Z>Z             <-illegal     (Z<Z) & (Z>Z)

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

array(nan)
array(0)
array([-9.22337204e+18])

In [ ]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_324/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 5 6 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.random.randint(0, 10, 5).astype(float)
B = np.random.randint(0, 10, 5).astype(float)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=A)

array([-44. ,  -0. , -30. , -40.5, -18. ])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
array17 = np.random.uniform(0,10,5)
print(array17//1)

[4. 9. 9. 5. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
array18 = np.tile(np.arange(5), (5,1))
print(array18)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array19 = np.random.rand(10)
array19.sort()
print(array19)

[0.10442691 0.21740969 0.29191472 0.30374839 0.55970604 0.60811131
 0.6358666  0.70573824 0.74605097 0.86349718]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
array20 = np.random.rand(10, 2)
a = np.sqrt(array20[:,0]**2+ array20[:,1]**2)
b = np.arctan2(array20[:,1],array20[:,0])
print(array20)
print(a)
print(b)

[[0.99422929 0.83481459]
 [0.25490603 0.93405926]
 [0.02318852 0.87241352]
 [0.70723122 0.42725382]
 [0.61681741 0.04691413]
 [0.95025815 0.20404308]
 [0.83660876 0.64396776]
 [0.39738719 0.33311579]
 [0.50472395 0.20517679]
 [0.20556012 0.93701899]]
[1.29823237 0.96821681 0.87272164 0.82626983 0.61859894 0.97191775
 1.0557503  0.51853901 0.54483371 0.9593016 ]
[0.69846046 1.30438226 1.54422285 0.54344475 0.07591222 0.21151219
 0.65601287 0.69764174 0.38610829 1.35484064]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
array21 = np.random.rand(10)
array21[array21.argmax()]=0
print(array21)

[0.33749994 0.92297249 0.62019733 0.46101274 0.57924131 0.91432551
 0.54247263 0.         0.22511089 0.10105929]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
array22 = np.arange(100)
array23 = np.random.uniform(0,100)
closest = array22[(np.abs(array22-array23)).argmin()]
print(array23)
print(closest)

17.46992531885615
17


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
column1

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z[Z[:,0].argsort()])

[[5 0 8]
 [6 9 5]
 [9 5 2]]


In [ ]:
column2

In [ ]:
print(Z[Z[:,1].argsort()])

[[5 0 8]
 [9 5 2]
 [6 9 5]]


In [ ]:
column3

In [ ]:
print(Z[Z[:,2].argsort()])

[[9 5 2]
 [6 9 5]
 [5 0 8]]
